name: Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Format check
        run: bun run format:check

      - name: Type check
        run: bun run check

      - name: Build
        run: bun run build

      - name: Zip
        run: bun run zip

      - name: Unit tests
        run: bun run test:unit

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: bun run test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
